name: scan_ai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/bg1.jpg
    - assets/bg4.jpg
    - assets/service1.jpg
    - assets/service2.jpg
    - assets/download.jpg
    - assets/scan_ai_video.mp4
    - assets/ecg_homeuse.png
    - assets/ecg_clinical.png
    - assets/ecg_hospital (2).png
    - assets/xray_handheld.jpeg
    - assets/xray_hospital.jpeg